#version 450
#extension GL_GOOGLE_include_directive : require

#include "ShaderInterop.h"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Clusters
{
    Cluster clusters[];
} s_clusters;

layout(binding = 1, rgba8) uniform image2D i_screenBuffer;

layout(push_constant) uniform PC
{
    ClusterDebugPushConstants pc;
};

void main()
{
    uvec2 pixelCoord = gl_GlobalInvocationID.xy;
    if (pixelCoord.x >= pc.screenSize.x || pixelCoord.y >= pc.screenSize.y)
    {
        return;
    }

    vec2 tileSize = pc.screenSize.xy / vec2(pc.clusterSize.xy);
    uvec2 tileCoord = uvec2(vec2(pixelCoord) / tileSize);

    uint baseClusterIdx = tileCoord.x + tileCoord.y * pc.clusterSize.x;

    uint lightCount = 0;
    for (uint z = 0; z < pc.clusterSize.z; ++z)
    {
        uint clusterIdx = baseClusterIdx + z * pc.clusterSize.x * pc.clusterSize.y;
        Cluster cluster = s_clusters.clusters[clusterIdx];
        for (int i = 0; i < 4; ++i)
        {
            lightCount += bitCount(cluster.litBits[i]);
        }
    }

    vec3 debugColor = vec3(0.0);
    if (lightCount == 0)
    {
        debugColor = vec3(0.1);
    }
    else if (lightCount <= 2)
    {
        debugColor = vec3(0.0, 0.5, 0.0);
    }
    else if (lightCount <= 4)
    {
        debugColor = vec3(0.0, 1.0, 0.0);
    }
    else if (lightCount <= 8)
    {
        debugColor = vec3(1.0, 1.0, 0.0);
    }
    else
    {
        debugColor = vec3(1.0, 0.0, 0.0);
    }

    vec3 sourceColor = imageLoad(i_screenBuffer, ivec2(pixelCoord)).rgb;
    float alpha = 0.5;
    vec3 finalColor = mix(sourceColor, debugColor, alpha);

    imageStore(i_screenBuffer, ivec2(pixelCoord), vec4(finalColor, 1.0));
}
