import os
import re
import sys


def FindGlslang():
    sdk = os.environ.get("VULKAN_SDK")
    if not sdk:
        raise RuntimeError("VULKAN_SDK environment variable not set")
    return os.path.join(sdk, "Bin", "glslangValidator.exe")


def ParseArguments(text):
    args = []
    current = ""
    inQuote = False
    for c in text:
        if c == '"':
            inQuote = not inQuote
        elif c == ',' and not inQuote:
            args.append(current.strip())
            current = ""
        else:
            current += c
    args.append(current.strip())
    return args


def ParseShaderList(path):
    entries = []
    currentBasePath = None

    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            match = re.match(r'REGISTER_SHADER\s*\(([^)]+)\)', line)
            if match:
                args = ParseArguments(match.group(1))
                currentBasePath = args[1].strip().strip('"')
                entries.append((currentBasePath, None, []))
                continue

            match = re.match(r'REGISTER_VARIANT\s*\(([^)]+)\)', line)
            if match:
                args = ParseArguments(match.group(1))
                variantName = args[1].strip()
                macros = [a.strip().strip('"') for a in args[2:]]
                entries.append((currentBasePath, variantName, macros))
                continue

    return entries


INCLUDE_RE = re.compile(r'^\s*#\s*include\s+(["<])([^">]+)[">]')


def ResolveInclude(includeName, currentDir, includeDirs):
    candidates = [os.path.join(currentDir, includeName)]
    for includeDir in includeDirs:
        candidates.append(os.path.join(includeDir, includeName))

    for candidate in candidates:
        if os.path.exists(candidate):
            return os.path.normpath(candidate)

    return None


def CollectIncludes(filePath, includeDirs, visited=None):
    if visited is None:
        visited = set()

    normalizedPath = os.path.normpath(filePath)
    if normalizedPath in visited or not os.path.exists(normalizedPath):
        return visited

    visited.add(normalizedPath)

    currentDir = os.path.dirname(normalizedPath)
    with open(normalizedPath, "r") as f:
        for line in f:
            match = INCLUDE_RE.match(line)
            if match:
                includeName = match.group(2)
                resolved = ResolveInclude(includeName, currentDir, includeDirs)
                if resolved:
                    CollectIncludes(resolved, includeDirs, visited)

    return visited


def MakeOutputPath(sourcePath, variantName):
    if variantName:
        dot = sourcePath.rfind('.')
        sourcePath = sourcePath[:dot] + "_" + variantName + sourcePath[dot:]

    slash = sourcePath.rfind('/')
    return sourcePath[:slash + 1] + "bin/" + sourcePath[slash + 1:] + ".spv"


def ToNinjaPath(path):
    return path.replace('\\', '/')


def GenerateNinja(projectDir, outputDir, entries, shaderDir, glslang):
    binDir = os.path.join(shaderDir, "bin")
    os.makedirs(binDir, exist_ok=True)
    os.makedirs(outputDir, exist_ok=True)

    includeDirs = [shaderDir]
    outputPath = os.path.join(outputDir, "shaders.ninja")

    with open(outputPath, "w") as f:
        f.write("# Auto-generated by GenerateShaderNinja.py\n\n")
        f.write("rule compile_shader\n")
        f.write(f"  command = {ToNinjaPath(glslang)} -V -I{ToNinjaPath(shaderDir)} --target-env vulkan1.3 $in -o $out $macros\n")
        f.write("  description = Compiling $out\n\n")

        for sourcePath, variantName, macros in entries:
            fullSourcePath = os.path.normpath(os.path.join(projectDir, "assets", sourcePath))
            outputSpvPath = MakeOutputPath(sourcePath, variantName)
            fullOutputPath = os.path.normpath(os.path.join(projectDir, "assets", outputSpvPath))

            includes = CollectIncludes(fullSourcePath, includeDirs)
            includes.discard(fullSourcePath)

            sourceRel = ToNinjaPath(os.path.relpath(fullSourcePath, projectDir))
            outputRel = ToNinjaPath(os.path.relpath(fullOutputPath, projectDir))
            includeRels = [ToNinjaPath(os.path.relpath(include, projectDir)) for include in sorted(includes)]

            macroArgs = " ".join(f"-D{macro}" for macro in macros)

            if includeRels:
                f.write(f"build {outputRel}: compile_shader {sourceRel} | {' '.join(includeRels)}\n")
            else:
                f.write(f"build {outputRel}: compile_shader {sourceRel}\n")
            f.write(f"  macros = {macroArgs}\n\n")

    print(f"Generated {outputPath} with {len(entries)} shader(s)")


def Main():
    if len(sys.argv) < 3:
        print("Usage: GenerateShaderNinja.py <project-dir> <output-dir>")
        sys.exit(1)

    projectDir = sys.argv[1]
    outputDir = sys.argv[2]

    shaderListPath = os.path.join(projectDir, "assets", "shaders", "shader_list.h")
    shaderDir = os.path.join(projectDir, "assets", "shaders")
    glslang = FindGlslang()

    entries = ParseShaderList(shaderListPath)
    GenerateNinja(projectDir, outputDir, entries, shaderDir, glslang)


if __name__ == "__main__":
    Main()
